# Generated by Django 4.2.2 on 2023-07-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='test_input',
            field=models.FileField(upload_to='input/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='test_output',
            field=models.FileField(upload_to='output/'),
        ),
    ]
