# Generated by Django 4.2.2 on 2023-07-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
