# Generated by Django 4.2.2 on 2023-07-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_tasks_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
