# Generated by Django 4.2.2 on 2023-07-10 22:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0006_alter_tasks_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Tasks",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
